name: scan_access
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 二维码
  qr_flutter: ^2.0.0
  # 全局状态管理
  scoped_model: ^1.0.1
  # webView
  webview_flutter: ^0.3.3
  # http请求库
  dio: ^2.0.11
  # 日期选择
  flutter_cupertino_date_picker: ^0.3.0
  # 图片选择和裁剪
  image_picker: ^0.5.0+3
  image_cropper: ^1.0.0
  # 首选项存储
  shared_preferences: ^0.5.1+1
  # 本地存储
  firebase_core: ^0.3.0
  firebase_storage: ^2.1.0+1
  # 吐司
  fluttertoast: ^3.0.1
  # 屏幕相关工具
  flutter_screenutil: ^0.5.0
  # 轮播
  flutter_swiper: ^1.1.4
  # 加载动画
  flutter_spinkit: ^3.1.0
  shimmer: ^1.0.0

#  uuid: ^1.0.0
#  video_player: 0.10.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/navigation_home_normal.png
  - images/navigation_home_selected.png
  - images/navigation_mine_normal.png
  - images/navigation_mine_selected.png
  - images/login_logo.png
  - images/mine_top_bg.png
  - images/header_icon_placeholder.png
  - images/setting.png
  - images/login_user.png
  - images/login_auth_code.png
  - images/login_password.png
  - images/mimabukejian.png
  - images/mimakejian.png
  - images/icon_check_update.png
  - images/icon_license.png
  - images/icon_mine_phone.png
  - images/icon_mine_setting.png
  - images/icon_mine_user.png
  - images/icon_set_pwd.png
  - images/right_back.png
  - images/show_qr_code_top_img.png
  - images/qr_code_placeholder.png
  - images/icon_community.png
  - images/icon_school.png
  - images/icon_factory.png
  - images/icon_office.png
  - images/icon_home_qr_code1.png
  - images/icon_home_qr_code2.png
  - images/icon_home_house.png
  - images/icon_home_family.png
  - images/scene_title_img.png
  - images/icon_logo.png
  - images/icon_user.png
  - images/icon_phone.png
  - images/icon_validate_time.png
  - images/icon_house.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
